### ISSUE TITLE
Case Study 7 - Headlines

### ISSUE THREAD

**Issue by dkpalmers** [BYUI335/M335_SP20_Rose_Noah#2]
Noah,
interesting approach with the for loops. As you point out, for loops are notoriously slow. It is easier to read and faster to use the tidyr and dplyr commands from the tidyverse. I encourage you to get familiar with those commands - though we will cover loops this week. I liked your visualizations of the by month mentions, well done. There were a couple of things I hoped you would notice in the real data that you don't see with the simulated stuff.

**Comment by NoahRose1** [comment]
I've update my case study with some of the code that we talked about in class today so that it now uses the actual data instead of my simulated data. Thank you Brother Palmer!
